name: '${version}'
version: '${version}'
main: 'trl.version.TRLVersion'
api-version: '1.21'
depend: [ProtocolLib]
softdepend: [ViaVersion]
author: 'TRL Team'
description: 'TRLVersion - All-in-one ViaVersion suite (Version support from 1.7.10 to 1.21+)'
website: 'https://github.com/chuyuewei/TRL-Plugin'
commands:
  trlversion:
    description: 'Check player version'
    usage: '/trlversion [player]'
    permission: 'trlversion.check'
  trlreload:
    description: 'Reload config'
    usage: '/trlreload'
    permission: 'trlversion.reload'